### PR TITLE
Added missing menu option to deploy EAC hack

### PR DESCRIPTION
**Pull request by cybex-dev**

### CODE REVIEW

**Comment by Termuellinator** [comment]
too early - i was seriously confused until i saw that this is for the cli-options ^^
But LGTM

**Comment by the-sane** [comment]
Thank you very much for the contribution!

The EAC workaround was (too optimistically) only ever meant to be in here very temporarily.  I deliberately avoided embedding it too deeply in the code, which meant not adding a CLI option nor integrating it into the pre-flight check.  That way, it would be quicker to remove once it was no longer needed. Unfortunately, here we are quite some time later and it's still needed. Although there appears to be hope right around the corner based on the leaked evocati patch notes!

I'm going to hold off on merging this for a little while to see if those hopes pan out. With a little luck, we can soon ditch the workaround entirely.

**Comment by cybex-dev** [comment]
@the-sane @Termuellinator and everyone else, seriously glad for your time and effort put into this. I only used the EAC option but what I saw, it had **alot** more features to explore.

*grab a beer at your favourite bar on me ;)

**Comment by the-sane** [comment]
Appreciate the kind words!  If you need any help, hit us up either on the LUG's Spectrum chat or our discord/matrix channels (they're bridged together).  
Links here: https://github.com/starcitizen-lug/information-howtos#socials

I will re-open this and merge it if the workaround is still needed for 3.17

**Pull request closed without merging**
