### PR TITLE
Fix: Make `ulimit -Hn` check more robust

### PR DESCRIPTION
**Pull request by x10an14**
Ref this issue encountered by me:
https://discord.com/channels/539464400734519306/608349808956276737/934071307463708712

In any regard, it should be preferable to check Lutris's limitations in the
*nix canonical way (checking /proc/PID/limits), as opposed to relying on
bash's builtin (`ulimit`).

### CODE REVIEW

**Comment by the-sane** [comment]
I really appreciate the PR!  It looks like a good idea to me.  One of my goals with the project is to keep the code as simple as possible so anyone can read it and understand what the script is doing.  To that end, I'd like to request some changes:

I think we can get away with an if statement instead of using the array and looping through it.  Something along these lines:

```
filelimit=lutris limit
if ( filelimit is null ); then
    filelimit=PPID limit
```

This can then be put in the filelimit_check and filelimit_confirm functions instead of its own function.

**Comment by x10an14** [comment]
> One of my goals with the project is to keep the code as simple as possible so anyone can read it and understand what the script is doing.

I hoped the comments clarified that. The purpose and intent of the array (prioritized order of limit checks - e.g. `ulimit` could be added back into the list if you really wanted it present) were understandable I hope?

It's a personally much preferred alternative to nested ifs. Since we can't early `return` in bash out of functions (to my knowledge).

> I think we can get away with an if statement instead of using the array and looping through it.

See above, but note that if you're happy with demanding the presence of lutris, there's just one necessary check in the loop. 
In which case I agree that the loop is overkill, and can be replaced by that singular, non-nested if statement.

Is that what you're requesting?

> This can then be put in the filelimit_check and filelimit_confirm functions instead of its own function.

I'm sorry, but I was not able to understand your intent with your pseudo-code... Maybe comment in-line with suggestions here on Github would be more productive/germane to the discussion?

**Comment by the-sane** [comment]
All that's really needed is this:

```
filelimit="$(awk '/Max open files/{ print $5 }' /proc/"$(pgrep lutris)"/limits)"
if [ -z "$filelimit" ]; then
    filelimit="$(awk '/Max open files/{ print $5 }' /proc/"$PPID"/limits)"
fi
```
Put that at the top of filelimit_check() and filelimit_confirm() and it will do the same thing, but is easier for novices to parse.

**Comment by the-sane** [comment]
Should probably pipe the output of the first awk command to /dev/null also to avoid it spitting out an error in the console when the next if statement handles the error case.

**Comment by x10an14** [comment]
# Note for posterity
Closing due to disagreement on chat with author of/maintainer wrt. rationale for implementing this change =)

I wanted this change primarily for more accuracy of limits checking (which rrequires depending on lutris), they don't want to add PR with that rationale/the proposed code change as-is.

I think both they and I agree that switch from `uimit` to `/proc/PID/limits` seems like a good change next time time is right to modify this code.

**Comment by the-sane** [comment]
Note to self: The current ulimit implementation is equivalent to checking the limit in `/proc/self/limits`.

**Pull request closed without merging**
