### PR TITLE
Update Lutris install script

### PR DESCRIPTION
**Pull request by beniwtv**
This updates our Lutris install script to be in line of what's now on Lutris.net:
- Add EAC file remove script from GE
- Update installer to latest from RSI

### CODE REVIEW

**Comment by the-sane** [comment]
Question: What's the benefit of having the installer delete that directory? Folks still have to use the Helper to add the hosts file workaround, right? The Helper would delete that directory at the same time if it exists..

**Comment by beniwtv** [comment]
It currently also uses the -SC wine from GE, so the workaround is not needed.

**Comment by the-sane** [comment]
Oh I see, so this step is needed here for anyone who won't be applying the workaround. Does that directory get created during installation or is it only created after the first launch of the game?

**Comment by beniwtv** [comment]
I think it's created after install, but the script is executed every time before the game launches.

**Comment by the-sane** [comment]
I don't love the idea of having it call a script off the internet, especially one that we don't control. From a security perspective, if someone took over the GE github, they could change the script to do anything. The burden would be on us to constantly verify that the script hasn't been changed to do anything we don't want it to do.

I think a better alternative would be to set the pre-run command to `/usr/bin/sh -c "if whatnot; then rm -rf stuff; fi"`  directly. It won't be as pretty, but it will be a lot more transparent to users than hiding it behind a script. The script method obfuscates what's really going on and someone who wants to inspect everything ends up having to also go inspect the script.

But if we really must call a script, I'd prefer if it was sourced from our own github.

Thoughts?

**Comment by beniwtv** [comment]
We could copy it to our GitHub and get it from there. Not sure if the pre-run command supports putting this in directly, but I can try.

I'll make the necessary changes.

**Comment by Termuellinator** [comment]
I agree it's not the best idea to call a script from somewhere - i don't assume this script changes very often anyway?

**Comment by the-sane** [comment]
This should work fine:

`/usr/bin/sh -c 'if [ -d "$WINEPREFIX/drive_c/users/$USER/AppData/Roaming/EasyAntiCheat" ]; then rm -rf "$WINEPREFIX/drive_c/users/$USER/AppData/Roaming/EasyAntiCheat"; fi'`

**Comment by beniwtv** [comment]
ok, the direct command works, we don't need a script. Also removed the "content" key in the JSON, as that is just a copy and not needed for Lutris to install SC.

**Comment by the-sane** [comment]
That's great, thanks!

**Comment by the-sane** [comment]
Is `discord_id` the id of our discord channel? Does that actually show up in the installer somewhere?

**Comment by beniwtv** [comment]
No idea, I haven't seen it pop up anywhere either

**Comment by the-sane** [comment]
Is it our discord channel though? Or did you just copy that from the lutris json?

**Comment by beniwtv** [comment]
I just copied it, I did not find a way to find the ID on Discord so far.

**Comment by the-sane** [comment]
If it's not our Discord, then it's just a link to the GE discord I guess? Or maybe the Lutris one? Either way, I don't think we really want that in ours. If it does show up as a clickable thing somewhere, people might go there asking questions about the Helper but that'd be the wrong place for that.

**Comment by the-sane** [comment]
I tried using a reverse lookup tool to figure out what account that ID is tied to, but it doesn't show up with a username, only a creation date. So either it's a deleted user or just a bot. Most likely, it's a bot and it's being used to track installs or something. Let's just get rid of it.

**Comment by beniwtv** [comment]
ok, removed the Discord ID and rebased the changes. I think it's ready now.

**Pull request merged**
