### PR TITLE
Add NixOS package to README

### PR DESCRIPTION
**Pull request by LovingMelody**
This adds the NixOS package to the read me

### CODE REVIEW

**Comment by the-sane** [comment]
Thanks!

Your referral code is already in there. I had added it when the last event was coming up since the other PR was hanging around for a while.

**Comment by LovingMelody** [comment]
Oh thanks, I didnt notice, ill remove that ocmmit

**Comment by LovingMelody** [comment]
Dropped the commit, should be good now.

**Comment by the-sane** [comment]
Thanks!

**Pull request merged**
